### ISSUE TITLE
There are RT issues

### ISSUE THREAD

**Issue by eserte** [ology/Music-Duration-Partition#1]
Please see https://rt.cpan.org/Ticket/Display.html?id=130757
Problem happens also for Music-Duration-Partition-0.0302

**Comment by ology** [comment]
eserte: Yes. I work the RT tickets, not duplicate github issues.  Please see the thread there.

Anyway, "Wed Nov 06 06:50:23 2019 gene@cpan.org - Fixed in 0.0303 added"
